// ponytail: a plain dictionary until the app has enough strings to justify i18next.
/** v1 speaks English. Hindi and Tamil are the next two; their strings live here
 *  so the screens do not have to change when they are switched on. */
export type Lang = "en" | "hi" | "ta";

export const LANGUAGES: { code: Lang; label: string; own: string; ready: boolean }[] = [
  { code: "en", label: "English", own: "English", ready: true },
  { code: "hi", label: "Hindi", own: "हिन्दी", ready: false },
  { code: "ta", label: "Tamil", own: "தமிழ்", ready: false },
];

const S = {
  hi: {
    appLine: "Order bolo, bill Qurie bhejegi, paisa Qurie yaad dilayegi.",
    start: "Shuru karein",
    pickLanguage: "Apni bhasha chunein",
    phoneTitle: "Apna mobile number likhein",
    phoneHint: "Is number par 6-digit code aayega",
    continue: "Aage badhein",
    otpTitle: "Code likhein",
    otpHint: (p: string) => `${p} par bheja gaya 6-digit code`,
    resend: "Dobara bhejein",
    resendIn: (s: number) => `Dobara bhejein (${s}s)`,
    verify: "Login karein",
    wrongCode: "Code galat hai",
    devCode: "Dev mode: code hai",
    shopTitle: "Apni dukaan ke baare mein batayein",
    ownerName: "Aapka naam",
    shopName: "Dukaan ka naam",
    shopType: "Dukaan ka type",
    address: "Dukaan ka pata",
    useLocation: "Abhi ki location se pata bharein",
    locating: "Location dhoondh rahe hain...",
    locationDenied: "Location ki permission nahi mili. Pata khud likh dein.",
    locationFailed: "Location nahi mili. Pata khud likh dein.",
    gstin: "GSTIN (optional)",
    city: "Sheher",
    save: "Save karein",
    later: "Baad mein",
    hardware: "Hardware",
    electrical: "Electrical",
    pharmacy: "Pharmacy",
    other: "Anya",
    greeting: (name: string) => `Namaste, ${name}!`,
    chatEmpty: "Pehla bill add karo, ya kuch poocho.",
    peopleEmpty: "Abhi koi supplier ya customer nahi.",
    suppliers: "Suppliers",
    customers: "Customers",
    chat: "Chat",
    people: "People",
    more: "More",
    language: "Bhasha",
    logout: "Logout",
    shop: "Dukaan",
    networkError: "Internet nahi mil raha. Phir try karo.",
    somethingWrong: "Kuch gadbad hui, phir try karo.",
    voiceStarting: 'Ek second...',
    voiceListening: 'Sun rahi hoon',
    voiceThinking: 'Soch rahi hoon...',
    voiceSpeaking: 'Qurie bol rahi hai',
    voiceFailed: 'Kuch gadbad hui',
    micDenied: 'Mic ki permission nahi mili. Address bar se mic allow karein.',
    micMissing: 'Koi microphone nahi mila.',
    micInsecure: 'Browser mic sirf localhost ya https par deta hai. Is PC par localhost:8081 kholein, ya phone par Expo Go.',
    noInternet: 'Abhi internet nahi hai.',
    filterAll: 'Sab',
    filterBills: 'Bill',
    filterPayments: 'Payment',
  },
  en: {
    appLine: "Speak the order. Qurie sends the bill and chases the money.",
    start: "Get started",
    pickLanguage: "Choose your language",
    phoneTitle: "Enter your mobile number",
    phoneHint: "A 6-digit code will be sent to this number",
    continue: "Continue",
    otpTitle: "Enter the code",
    otpHint: (p: string) => `6-digit code sent to ${p}`,
    resend: "Resend code",
    resendIn: (s: number) => `Resend in ${s}s`,
    verify: "Log in",
    wrongCode: "Wrong code",
    devCode: "Dev mode: the code is",
    shopTitle: "Tell us about your shop",
    ownerName: "Your name",
    shopName: "Shop name",
    shopType: "Shop type",
    address: "Shop address",
    useLocation: "Fill address from current location",
    locating: "Finding your location...",
    locationDenied: "Location permission was not given. Type the address instead.",
    locationFailed: "Could not get the location. Type the address instead.",
    gstin: "GSTIN (optional)",
    city: "City",
    save: "Save",
    later: "Later",
    hardware: "Hardware",
    electrical: "Electrical",
    pharmacy: "Pharmacy",
    other: "Other",
    greeting: (name: string) => `Good morning, ${name}!`,
    chatEmpty: "Add your first bill, or ask me something.",
    peopleEmpty: "No suppliers or customers yet.",
    suppliers: "Suppliers",
    customers: "Customers",
    chat: "Chat",
    people: "People",
    more: "More",
    language: "Language",
    logout: "Log out",
    shop: "Shop",
    networkError: "No internet. Try again.",
    somethingWrong: "Something went wrong. Try again.",
    voiceStarting: 'One moment...',
    voiceListening: 'Listening',
    voiceThinking: 'Thinking...',
    voiceSpeaking: 'Qurie is speaking',
    voiceFailed: 'Something went wrong',
    micDenied: 'No microphone permission. Allow the mic from the address bar.',
    micMissing: 'No microphone found.',
    micInsecure: 'The browser only gives mic access on localhost or https. Open localhost:8081 on this computer, or use Expo Go on a phone.',
    noInternet: 'No internet right now.',
    filterAll: 'All',
    filterBills: 'Bills',
    filterPayments: 'Payments',
  },
  ta: {
    appLine: "ஆர்டரைச் சொல்லுங்கள். Qurie பில் அனுப்பும், பணத்தையும் நினைவூட்டும்.",
    start: "தொடங்குங்கள்",
    pickLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுங்கள்",
    phoneTitle: "உங்கள் மொபைல் எண்ணை உள்ளிடுங்கள்",
    phoneHint: "இந்த எண்ணுக்கு 6 இலக்கக் குறியீடு அனுப்பப்படும்",
    continue: "தொடரவும்",
    otpTitle: "குறியீட்டை உள்ளிடுங்கள்",
    otpHint: (p: string) => `${p} க்கு அனுப்பப்பட்ட 6 இலக்கக் குறியீடு`,
    resend: "மீண்டும் அனுப்பு",
    resendIn: (s: number) => `மீண்டும் அனுப்ப ${s}வி`,
    verify: "உள்நுழைக",
    wrongCode: "குறியீடு தவறு",
    devCode: "Dev mode: குறியீடு",
    shopTitle: "உங்கள் கடையைப் பற்றிச் சொல்லுங்கள்",
    ownerName: "உங்கள் பெயர்",
    shopName: "கடையின் பெயர்",
    shopType: "கடை வகை",
    address: "கடையின் முகவரி",
    useLocation: "தற்போதைய இருப்பிடத்திலிருந்து முகவரியை நிரப்பு",
    locating: "இருப்பிடத்தைத் தேடுகிறோம்...",
    locationDenied: "இருப்பிட அனுமதி வழங்கப்படவில்லை. முகவரியை நீங்களே தட்டச்சு செய்யுங்கள்.",
    locationFailed: "இருப்பிடம் கிடைக்கவில்லை. முகவரியை நீங்களே தட்டச்சு செய்யுங்கள்.",
    gstin: "GSTIN (விரும்பினால்)",
    city: "நகரம்",
    save: "சேமி",
    later: "பிறகு",
    hardware: "ஹார்ட்வேர்",
    electrical: "எலெக்ட்ரிக்கல்",
    pharmacy: "மருந்தகம்",
    other: "மற்றவை",
    greeting: (name: string) => `வணக்கம், ${name}!`,
    chatEmpty: "முதல் பில்லைச் சேர்க்கவும், அல்லது என்னிடம் கேளுங்கள்.",
    peopleEmpty: "இன்னும் சப்ளையர் அல்லது கஸ்டமர் இல்லை.",
    suppliers: "சப்ளையர்கள்",
    customers: "கஸ்டமர்கள்",
    chat: "அரட்டை",
    people: "நபர்கள்",
    more: "மேலும்",
    language: "மொழி",
    logout: "வெளியேறு",
    shop: "கடை",
    networkError: "இணையம் இல்லை. மீண்டும் முயற்சிக்கவும்.",
    somethingWrong: "ஏதோ தவறு நடந்தது. மீண்டும் முயற்சிக்கவும்.",
    voiceStarting: 'ஒரு நிமிடம்...',
    voiceListening: 'கேட்கிறேன்',
    voiceThinking: 'யோசிக்கிறேன்...',
    voiceSpeaking: 'Qurie பேசுகிறது',
    voiceFailed: 'ஏதோ தவறு நடந்தது',
    micDenied: 'மைக் அனுமதி இல்லை. அட்ரஸ் பாரில் மைக்கை அனுமதிக்கவும்.',
    micMissing: 'மைக்ரோஃபோன் கண்டறியப்படவில்லை.',
    micInsecure: 'உலாவி localhost அல்லது https இல் மட்டுமே மைக் அனுமதிக்கும். இந்தக் கணினியில் localhost:8081 திறக்கவும், அல்லது தொலைபேசியில் Expo Go.',
    noInternet: 'இப்போது இணையம் இல்லை.',
    filterAll: 'அனைத்தும்',
    filterBills: 'பில்கள்',
    filterPayments: 'பணம்',
  },
} as const;

export type Strings = (typeof S)["en"];

export function strings(lang: Lang): Strings {
  return S[lang] as Strings;
}
